api_login_check:
  path: /api/login_check
api_register:
  path: /api/register
  controller: App\Controller\AuthController::register
api_user:
  path: /api/user
  controller: App\Controller\AuthController::getUserInfo
app_list:
  path: /api/list
  controller: App\Controller\ListController::index
app_images:
  path: /api/image
  controller: App\Controller\ImageController::getImage
