api_login_check:
  path: /api/login_check
api_register:
  path: /api/register
  controller: App\Controller\AuthController::register
api_user:
  path: /api/user
  controller: App\Controller\AuthController::getUserInfo
api_product_list:
  path: /api/product
  controller: App\Controller\ProductController::index
api_product_delete:
  path: /api/product/delete
  controller: App\Controller\ProductController::delete
api_product_create:
  path: /api/product/create
  controller: App\Controller\ProductController::create
api_categories:
  path: /api/categories
  controller: App\Controller\CategoryController::index
api_images:
  path: /api/image
  controller: App\Controller\ImageController::getImage
